### ISSUE TITLE
Pressing just Ctrl opens help

### ISSUE THREAD

**Issue by TheDrone7** [QB64Official/vscode#124]
While I am working on code, I often press `Ctrl` + `S` to save my code. But I realized, that if my cursor is on a token, it tries to show help for the token. This often just opens the help file in a new tab before I can even save my code.

With a little bit of more investigation, I found out that it happens on pressing just `Ctrl` (key-down event probably because it often happens before I even get to the `S` to save).

What's weirder is it is not there in any of my keybindings (screenshot attached) but is only an issue while the extension is installed/enabled.

![image](https://github.com/QB64Official/vscode/assets/38010647/ece3f89d-ecda-44d1-9608-b77f587675aa)

**Comment by LordDurus** [comment]
This was fixed in the April release of VSCode (I think) 
This is the same issue that is in https://github.com/QB64Official/vscode/issues/61

There used to be a setting added  that was added settings.json when it was created, but after the VSCode change the issue quit happening.  So it was removed.  

Here is the setting to add to the launch.json "editor.multiCursorModifier": "ctrlCmd"  It doesn't fix the problem just moves to the alt key.   So somewhat better.

A few Qustions:
1) What version of VSCode are you using?
2) What version of the extension?
3) What OS is this happening in?

If you're still having the issue on the latest extension and latest VSCode then this is still an issue.

**Comment by LordDurus** [comment]
After some more testing I am able to recreate this with the latest VSCode and extension.

Add the setting does help with the issue.
![image](https://github.com/QB64Official/vscode/assets/2650021/ce4d2482-9b94-427e-b6f6-d66a5a60d71d)

**Comment by LordDurus** [comment]
I added the multiCursorModifier back to the auto created settings.json. 
This will not updated existing settings.json.   You will either need to edit yours or all the extension to create a new one.

This is in the latest v0.9.1

**Comment by TheDrone7** [comment]
Sorry for the delayed response but lgtm now, gonna close this.
